// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjfxx3A8DHwoCwffDH3h5cnfxHRikLzQI',
    appId: '1:620012359691:web:677efab3ffbdfc2e73770e',
    messagingSenderId: '620012359691',
    projectId: 'alikay-shop',
    authDomain: 'alikay-shop.firebaseapp.com',
    databaseURL: 'https://alikay-shop-default-rtdb.firebaseio.com',
    storageBucket: 'alikay-shop.appspot.com',
    measurementId: 'G-E6MDDTDY2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe6zM-5CnYYEPAw_9amujlZPR9iGkjfB8',
    appId: '1:620012359691:android:bd906ba43fad4ccd73770e',
    messagingSenderId: '620012359691',
    projectId: 'alikay-shop',
    databaseURL: 'https://alikay-shop-default-rtdb.firebaseio.com',
    storageBucket: 'alikay-shop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtSaW7GZ0_Gv8XLlDvxjXDnZI10IFXe-A',
    appId: '1:620012359691:ios:585e09aa1fb850c673770e',
    messagingSenderId: '620012359691',
    projectId: 'alikay-shop',
    databaseURL: 'https://alikay-shop-default-rtdb.firebaseio.com',
    storageBucket: 'alikay-shop.appspot.com',
    androidClientId: '620012359691-1jb0e9rp9poldlpoubqpg6ha8csulv9r.apps.googleusercontent.com',
    iosClientId: '620012359691-mg8pgkuu8m5rdp27n4n6076ofbod7fu3.apps.googleusercontent.com',
    iosBundleId: 'com.example.resumeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtSaW7GZ0_Gv8XLlDvxjXDnZI10IFXe-A',
    appId: '1:620012359691:ios:53b96cd02e03e3e973770e',
    messagingSenderId: '620012359691',
    projectId: 'alikay-shop',
    databaseURL: 'https://alikay-shop-default-rtdb.firebaseio.com',
    storageBucket: 'alikay-shop.appspot.com',
    androidClientId: '620012359691-1jb0e9rp9poldlpoubqpg6ha8csulv9r.apps.googleusercontent.com',
    iosClientId: '620012359691-boti3hl3o2u5dp6nkq9f58h7s7uim7oh.apps.googleusercontent.com',
    iosBundleId: 'com.example.resumeApp.RunnerTests',
  );
}
